---
- name: Attempting to overlay resilio-sync yum repository
  tags: resilio_sync
  become: true
  yum_repository:
    baseurl: 'http://linux-packages.resilio.com/resilio-sync/rpm/$basearch'
    description: 'Resilio Sync $basearch'
    enabled: yes
    gpgkey: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-resilio-sync'
    gpgcheck: yes
    name: resilio-sync
    state: present

- name: Downloading the resilio-sync gpg key to store locally
  tags: resilio_sync
  become: true
  get_url:
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-resilio-sync
    owner: root
    group: root
    mode: 0644
    url: 'https://linux-packages.resilio.com/resilio-sync/key.asc'

- name: Ensure that the resilio-sync gpg key is installed
  tags: resilio_sync
  become: true
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-resilio-sync
    state: present

- name: Ensure that the resilio-sync package is installed
  tags: resilio_sync
  become: true
  yum:
   enablerepo: resilio-sync
   name: resilio-sync
   state: present

- name: Attempting to gather a list of system groups, if applicable
  tags: resilio_sync
  getent:
    database: group
    split: ':'
  when: rslsync_groups|length > 0

- name: Attempting to append rslsync user to groups, if applicable
  tags: resilio_sync
  become: true
  user:
    append: yes
    groups: "{{ item }}"
    name: rslsync
  loop: "{{ rslsync_groups }}"
  loop_control:
    label: "{{ item }}"
  when:
    - item in getent_group
    - rslsync_groups|length > 0

- name: Attempting to create hidden sync directories, if applicable
  tags: resilio_sync
  become: true
  file:
    path: "{{ item.value.dir }}/.sync"
    owner: rslsync
    group: rslsync
    mode: 0775
    state: directory
  loop: "{{ rslsync_shared_folders|dict2items|sort }}"
  loop_control:
    label: "{{ item.value.dir }}"
  when:
    - item.value.dir is defined
    - rslsync_shared_folders|length > 0

- name: Attempting to overlay resilio-sync configurations
  tags: resilio_sync
  become: true
  template:
    src: config.json.j2
    dest: /etc/resilio-sync/config.json
    owner: root
    group: root
    mode: 0644
  notify: restart resilio-sync

- name: Ensure that resilio-sync is started and enabled on boot
  service:
    enabled: yes
    name: resilio-sync
    state: started
...
