---
- name: Attempting to gather a list of system groups, if applicable
  getent:
    database: group
    split: ':'
  when: rslsync_groups|length > 0

- name: Attempting to append rslsync user to groups, if applicable
  user:
    append: yes
    groups: "{{ item }}"
    name: rslsync
  loop: "{{ rslsync_groups }}"
  loop_control:
    label: "{{ item }}"
  when:
    - item in getent_group
    - rslsync_groups|length > 0
...
